account/urls.py
from django.contrib.auth import views as user_view
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from . import views

app_name = 'account'
# pre-urls = 'account/'
urlpatterns = [
    path('login/', user_view.LoginView.as_view(), name='login'),
    path('logout/', user_view.LogoutView.as_view(), name='logout'),
    #
    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #
    # path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns += [
    path('api/', include('account.api.urls'), name='account_api'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('create/', views.MovieCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.MovieUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.MovieDeleteView.as_view(), name='delete'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
]

movie_app/api/urls.py
from rest_framework import routers
from django.urls import path, include

from . import views

# api
# router = routers.DefaultRouter()
# router.register('movie', views.MovieApiView)
# pre-urls = 'movie/api/'
urlpatterns = [
    # path('', include(router.urls), name='movie'),
    path('movie/', views.MovieListApiView.as_view(), name='movie_list'),
    path('movie/<int:pk>', views.MovieDetailApiView.as_view(), name='movie_detail'),
    path('cast/', views.CastListApiView.as_view(), name='cast_list'),
    path('cast/<int:pk>/', views.CastDetailApiView.as_view(), name='cast_detail'),
]

movie_app/urls.py
from django.urls import path, include
from . import views


app_name = 'movie_app'
# pre-urls = 'movie/'
urlpatterns = [
    path('api/', include('movie_app.api.urls'), name='movie_app_api'),

    path('', views.HomeView.as_view(), name='home'),
    path('mv-<int:pk>/<slug:slug>', views.MovieDetailView.as_view(), name='movie_detail'),
    path('genre/<str:genre>', views.GenreListView.as_view(), name='genre_list'),
    path('year/<int:year>', views.YearDateArchiveView.as_view(), name='year_archive'),
    path('language/<str:language>', views.LanguageListView.as_view(), name='language_list'),
    path('search', views.SearchListView.as_view(), name='search_list'),
]

movie_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/', include('movie_app.urls')),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_app/models.py
from datetime import datetime

from django.db import models
from account.models import User
from django_jalali.db import models as jmodels
from django.utils.html import format_html
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy


class CastModel(models.Model):
    name = models.CharField(max_length=50, verbose_name='نام')
    age = models.IntegerField(verbose_name='سن')

    class Meta:
        verbose_name = 'بازیگر'
        verbose_name_plural = 'بازیگران'

    def __str__(self):
        return self.name


class MovieModel(models.Model):
    class Language(models.TextChoices):
        ENGLISH = _('english')
        FARSI = _('farsi')

    PUBLISHED_CHOICES = (
        (True, _('منتشر شده')),
        (False, _('منتشر نشده'))
    )

    IS_GOLD_MOVIE_CHOICES = (
        (True, _('طلایی')),
        (False, _('عادی'))
    )

    YEAR_CHOICES = []
    for r in range(2010, datetime.now().year + 1):
        YEAR_CHOICES.append((r, r))

    name = models.CharField(max_length=50, verbose_name='نام')
    description = models.TextField(verbose_name='توضیحات')
    cover = models.ImageField(upload_to='movie_model/images/cover/',
                              verbose_name='تصویر کاور')
    trailer_link = models.CharField(max_length=250, verbose_name='لینک پیش نمایش')
    language = models.CharField(choices=Language.choices, max_length=50,
                                verbose_name='زبان فیلم')
    # year = jmodels.jDateField(verbose_name='تاریخ ساخت فیلم')
    year = models.IntegerField(choices=YEAR_CHOICES,
                               default=datetime.now().year,
                               verbose_name='تاریخ ساخت فیلم')
    genres = models.ForeignKey('GenresModel', on_delete=models.SET_NULL,
                               verbose_name='ژانر', null=True)
    download_link = models.URLField(verbose_name='لینک دانلود')
    watch_link = models.URLField(verbose_name='لینک نمایش')
    view = models.PositiveIntegerField(verbose_name='تعداد بازدید')
    rate = models.DecimalField(
        default=0, validators=[MinValueValidator(0.0), MaxValueValidator(5.0)],
        max_digits=2, decimal_places=1,
        blank=True, null=True, verbose_name='امتیاز'
    )
    slider_pic = models.ImageField(upload_to='movie_model/images/slider_pic/',
                                   null=True, blank=True, verbose_name='تصویر اسلایدر')
    cast = models.ManyToManyField(CastModel, verbose_name='بازیگران')
    slug = models.SlugField(max_length=40, allow_unicode=True, unique=True, blank=True,
                            verbose_name='نامک')
    published = models.BooleanField(choices=PUBLISHED_CHOICES, verbose_name='وضعیت انتشار')
    publisher = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name='نویسنده مطلب')
    is_gold_movie = models.BooleanField(default=False, choices=IS_GOLD_MOVIE_CHOICES, verbose_name='وضعیت دسترسی طلایی')

    class Meta:
        verbose_name = 'فیلم'
        verbose_name_plural = 'فیلم ها'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:  # blank slug input
            self.slug = slugify(self.name, allow_unicode=True)
        else:
            self.slug = slugify(self.slug, allow_unicode=True)

        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('account:home')

    def thumbnail_tag(self):
        return format_html('<img width=75 height=100 style="border-radius: 10px;" src="{}">'.format(self.cover.url))

    thumbnail_tag.short_description = 'پیشنمایش کاور'


class SliderPic(models.Model):
    movie_model = models.ForeignKey('MovieModel', on_delete=models.CASCADE,
                                    verbose_name='انتخاب فیلم')

    class Meta:
        verbose_name = 'اسلایدر'
        verbose_name_plural = 'اسلایدرها'

    def clean(self):
        if not self.movie_model.slider_pic:
            raise ValidationError('slider_pic of "{}" is empty'.format(self.movie_model))

    def __str__(self):
        return self.movie_model.name + ' Slider'


class GenresModel(models.Model):
    genres_type = models.ForeignKey('self', on_delete=models.SET_NULL,
                                    null=True, blank=True,
                                    verbose_name='زیر منوی ژانر')
    genres = models.CharField(max_length=50, verbose_name='ژانر')
    level = models.PositiveIntegerField(verbose_name='سطح', blank=True)

    class Meta:
        verbose_name = 'ژانر'
        verbose_name_plural = 'ژانرها'

    def __str__(self):
        return self.genres

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self.genres_type:
            self.level = self.genres_type.level + 1
        else:
            self.level = 1

        return super().save()

movie_app/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(label='',
                             max_length=10,
                             widget=forms.TextInput(
                                 attrs={
                                     'name': 'q',
                                     'class': 'searchfield',
                                     'placeholder': 'Search...',
                                 }),
                             )

movie_app/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics, mixins

from movie_app.api.serializers import MovieSerializer, CastSerializer, CastSerializer2
from ..models import MovieModel, CastModel


# class MovieApiView(viewsets.ModelViewSet):
#     queryset = MovieModel.objects.all()
#     serializer_class = MovieSerializer

class MovieListApiView(generics.ListAPIView):
    queryset = MovieModel.objects.all()
    serializer_class = MovieSerializer


class MovieDetailApiView(generics.RetrieveUpdateAPIView):
    queryset = MovieModel.objects.all()
    serializer_class = MovieSerializer


# class CastListApiView(APIView):
#
#     def get(self, request):
#         casts = CastModel.objects.all()
#         data = CastSerializer(casts, many=True).data
#         return Response(data=data)


# class CastDetailApiView(APIView):
#
#     def get(self, request, pk):
#         cast = get_object_or_404(CastModel, pk=pk)
#         data = CastSerializer(cast).data
#         return Response(data=data)


class CastListApiView(generics.ListCreateAPIView):
    queryset = CastModel.objects.all()

    def get_serializer_class(self):
        if self.request.user.is_authenticated:
            return CastSerializer
        return CastSerializer2


class CastDetailApiView(generics.RetrieveUpdateDestroyAPIView):
    queryset = CastModel.objects.all()
    serializer_class = CastSerializer

movie_app/views.py
from __future__ import annotations

from django.db.models import Q
from django.shortcuts import get_list_or_404
from django.views.generic import ListView, DetailView, TemplateView, YearArchiveView

from .models import MovieModel, SliderPic


class HomeView(ListView):
    model = MovieModel
    template_name = "movie_app/index.html"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['slider_object_list'] = SliderPic.objects.all()
        return context


class MovieDetailView(DetailView):
    model = MovieModel
    template_name = "movie_app/movie_detail.html"
    query_pk_and_slug = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['related_movies'] = MovieModel.objects.exclude(slug=kwargs.get('object').slug)[:6]
        return context


class GenreListView(ListView):
    model = MovieModel
    template_name = "movie_app/genre.html"
    paginate_by = 5

    def get_queryset(self, **kwargs):
        object_list = get_list_or_404(self.model, genres__genres=self.kwargs.get('genre'))
        return object_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genre'] = self.kwargs.get('genre')
        return context


# class YearDateArchiveView(YearArchiveView):
#     queryset = MovieModel.objects.all()
#     date_field = 'year'
#     template_name = 'movie_app/year.html'
#     paginate_by = 5
#     make_object_list = True
#     allow_future = True
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['year'] = self.kwargs.get('year')
#         return context


class YearDateArchiveView(ListView):
    model = MovieModel
    template_name = 'movie_app/year.html'
    paginate_by = 5

    def get_queryset(self, **kwargs):
        object_list = get_list_or_404(self.model, year=self.kwargs.get('year'))
        return object_list


class LanguageListView(ListView):
    model = MovieModel
    template_name = 'movie_app/language.html'
    paginate_by = 5

    def get_queryset(self, **kwargs):
        object_list = get_list_or_404(self.model, language=self.kwargs.get('language'))
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['language'] = self.kwargs.get('language')
        return context


class SearchListView(ListView):
    model = MovieModel
    template_name = 'movie_app/search.html'
    paginate_by = 5

    def get_queryset(self, **kwargs):
        search_char = self.request.GET.get('q')
        if search_char:
            object_list = MovieModel.objects.filter(
                Q(name__icontains=search_char) |
                Q(cast__name__icontains=search_char)
            ).distinct()
        else:
            object_list = self.model.objects.none()
        return object_list

movie_app/templates/movie_app/base.html
{% load static %}
{% load auto_navbar %}

<!DOCTYPE html>
<html lang="en">

<head>
  {% block head %}

    <meta charset="utf-8">

    <title>
      {% block title %}
        Movies
      {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    <!-- Link Swiper's CSS -->
    <link rel="stylesheet" href="{% static 'movie_app/css/swiper.min.css' %}">
    <link rel="stylesheet" href="{% static 'movie_app/css/styles.css' %}">

    <script src="{% static 'movie_app/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'movie_app/js/script.js' %}"></script>

    {% block add_head_eleman %}{% endblock add_head_eleman %}

    <!-- Demo styles -->
    <style>
      [_] {
        box-shadow: 0 0 0 99999px rgba(0, 0, 0, .7);
        position: relative;
        z-index: 9999;
        pointer-events: auto;
        border: 3px dashed deepskyblue;
      }

      [_] > * {
        border: 1px dashed lawngreen;
      }

      {% block style %}{% endblock %}
    </style>
  {% endblock head %}

</head>

<body>
{% block body %}

  <div class="wrapper">

    <header class="header">
      {% block header %}
        <figure class="logo">
          <a href="{% url 'movie_app:home' %}"><img src="{% static 'movie_app/img/logo.png' %}" alt="Logo"></a>
        </figure>
        <nav class="menu">
          <ul>
            {% auto_nav %}
            <li class="mobsearch">
              <form class="mobform" method="get" action="{% url 'movie_app:search_list' %}">
                <input type="text" name="q" class="mobsearchfield" value="{{ request.GET.q }}" placeholder="Search...">
                <input type="submit" value="" class="mobsearchsubmit">
              </form>
            </li>
          </ul>
        </nav>
        <form class="search" action="{% url 'movie_app:search_list' %}" method="get">
          <input type="text" name="q" value="{{ request.GET.q }}" class="searchfield" placeholder="Search...">
          <input type="submit" value="" class="searchsubmit">
        </form>
        <div class="toggle">
          <img src="{% static 'movie_app/img/menu.svg' %}">
        </div>
        <div class="menu">
          <ul>
            <li>
              <a href="/admin">admin</a>
            </li>
            <li>
              <a href="{% url 'account:login' %}">login</a>
            </li>
            <li>
              <a href="{% url 'account:logout' %}">logout</a>
            </li>
          </ul>
        </div>
      {% endblock header %}
    </header>

    <!-- Swiper -->

    {% block slider %}
    {% endblock slider %}

    <main class="content">
      {% block content %}
      {% endblock content %}
    </main>

    <footer class="footer">
      {% block footer %}
        <div class="copyright">
          <p>Copyright &copy 2017 www.focusoncode.com</p>
        </div>
        <div class="footermenu">
          <ul>
            <li>
              <a href="{% url 'movie_app:home' %}">Home</a>
            </li>
            <li>
              <a href="contact.html">Contact</a>
            </li>
            <li>
              <a href="terms.html">Terms and conditions</a>
            </li>
          </ul>
        </div>
        <div class="tags">
          <ul>
            <li>Watch Free Movies Trailers</li>
            <li>Movie Trailers</li>
            <li>English Subtitled Movies Trailers</li>
            <li>Latest Movies Trailers</li>
            <li>New Movies Trailers</li>
          </ul>
        </div>
      {% endblock footer %}
    </footer>

    {% block script %}
    <!-- Swiper JS -->
      <script src="{% static 'movie_app/js/swiper.min.js' %}"></script>

    <!-- Initialize Swiper -->
      <script>
          $(document).ready(function () {


              var swiper = new Swiper(".homeslider > .swiper-container", {
                  pagination: ".swiper-pagination",
                  paginationClickable: true,
                  preventClicks: false,
                  preventClicksPropagation: false,
                  effect: "fade",
                  breakpoints: {
                      320: {
                          height: 200
                      },

                      480: {
                          height: 300
                      },

                      768: {
                          height: 400
                      },
                      1024: {
                          height: 500
                      }
                  }
              });

              var recentswiper = new Swiper(".recentslider > .swiper-container", {
                  nextButton: ".recent-next",
                  prevButton: ".recent-prev",
                  slidesPerView: 8,
                  paginationClickable: true,
                  preventClicks: false,
                  preventClicksPropagation: false,
                  spaceBetween: 10,
                  breakpoints: {
                      320: {
                          slidesPerView: 3,
                          spaceBetween: 5
                      },

                      480: {
                          slidesPerView: 3,
                          spaceBetween: 5
                      },

                      768: {
                          slidesPerView: 5,
                          spaceBetween: 5
                      },
                      1024: {
                          slidesPerView: 6,
                          spaceBetween: 10
                      }
                  }
              });

              var mostswiper = new Swiper(".mostslider > .swiper-container", {
                  nextButton: ".most-next",
                  prevButton: ".most-prev",
                  slidesPerView: 8,
                  paginationClickable: true,
                  preventClicks: false,
                  preventClicksPropagation: false,
                  spaceBetween: 10,
                  breakpoints: {
                      320: {
                          slidesPerView: 3,
                          spaceBetween: 5
                      },

                      480: {
                          slidesPerView: 3,
                          spaceBetween: 5
                      },

                      768: {
                          slidesPerView: 5,
                          spaceBetween: 5
                      },
                      1024: {
                          slidesPerView: 6,
                          spaceBetween: 10
                      }
                  }
              });

              var topswiper = new Swiper(".topslider > .swiper-container", {
                  nextButton: ".top-next",
                  prevButton: ".top-prev",
                  slidesPerView: 8,
                  paginationClickable: true,
                  preventClicks: false,
                  preventClicksPropagation: false,
                  spaceBetween: 10,
                  breakpoints: {
                      320: {
                          slidesPerView: 3,
                          spaceBetween: 5
                      },

                      480: {
                          slidesPerView: 3,
                          spaceBetween: 5
                      },

                      768: {
                          slidesPerView: 5,
                          spaceBetween: 5
                      },
                      1024: {
                          slidesPerView: 6,
                          spaceBetween: 10
                      }
                  }
              });

          });


      </script>
    {% endblock script %}

  </div>

{% endblock body %}
</body>
</html>

movie_app/templates/movie_app/genre.html
{% extends 'movie_app/list_views_base.html' %}
{% load static %}


{% block content_list %}
  <h3>{{ genre }}</h3>
  <div class="movies">
    {% for object in object_list %}
      <div class="mov">
        <a href="{% url 'movie_app:movie_detail' object.pk object.slug %}">
          <img src="{{ object.cover.url }}">
          <h2 class="movietitle">{{ object.name }}</h2>
        </a>
      </div>
    {% endfor %}
  </div>
{% endblock content_list %}

movie_app/templates/movie_app/index.html
{% extends 'movie_app/base.html' %}
{% load static %}


<!-- Swiper -->
{% block slider %}
  <div class="homeslider">
    <div class="swiper-container">
      <div class="swiper-wrapper">

        {% for slider_object in slider_object_list %}
          <div class="swiper-slide">
            <img src="{{ slider_object.movie_model.slider_pic.url }}">
            <div class="caption">
              <div class="captioninside">
                <h3>{{ slider_object.movie_model.name }}</h3>
                <p>{{ slider_object.movie_model.description }}</p>
                <a href="{% url 'movie_app:movie_detail' slider_object.movie_model.pk slider_object.movie_model.slug %}"
                   class="playbutton">Play</a>
              </div>
            </div>
          </div>
        {% endfor %}

      </div>
      <!-- Add Pagination -->
      <div class="swiper-pagination"></div>
    </div>
  </div>
{% endblock slider %}
{% block content %}
  <section class="panel">
    <h2>Recently Added</h2>
    <div class="recentslider">
      <div class="swiper-container">
        <div class="swiper-wrapper">
          {% for object in object_list %}
            <div class="swiper-slide">
              <a href="{% url 'movie_app:movie_detail' object.pk object.slug %}"><img src="{{ object.cover.url }}">
                <h3 class="hometitle">{{ object.name }}</h3></a>
            </div>
          {% endfor %}
          <div class="swiper-slide">
            <a href="movie_list.html"><img src="{% static 'movie_app/img/others.png' %}"></a>
          </div>
        </div>
        <div class="nextdirection recent-next">
          <img src="{% static 'movie_app/img/right-arrow.svg' %}">
        </div>
        <div class="leftdirection recent-prev">
          <img src="{% static 'movie_app/img/left-arrow.svg' %}">
        </div>
      </div>
    </div>
  </section>
  <section class="panel">
    <h2>Most Watched</h2>
    <div class="mostslider">
      <div class="swiper-container">
        <div class="swiper-wrapper">
          {% for object in object_list %}
            <div class="swiper-slide">
              <a href="{% url 'movie_app:movie_detail' object.pk object.slug %}"><img src="{{ object.cover.url }}">
                <h3 class="hometitle">{{ object.name }}</h3></a>
            </div>
          {% endfor %}
          <div class="swiper-slide">
            <a href="movie_list.html"><img src="{% static 'movie_app/img/others.png' %}"></a>
          </div>
        </div>
        <div class="nextdirection most-next">
          <img src="{% static 'movie_app/img/right-arrow.svg' %}">
        </div>
        <div class="leftdirection most-prev">
          <img src="{% static 'movie_app/img/left-arrow.svg' %}">
        </div>
        <!-- Add Pagination -->
      </div>
    </div>
  </section>
  <section class="panel">
    <h2>Top Rated</h2>
    <div class="topslider">
      <div class="swiper-container">
        <div class="swiper-wrapper">
          {% for object in object_list %}
            <div class="swiper-slide">
              <a href="{% url 'movie_app:movie_detail' object.pk object.slug %}"><img src="{{ object.cover.url }}">
                <h3 class="hometitle">{{ object.name }}</h3></a>
            </div>
          {% endfor %}
          <div class="swiper-slide">
            <a href="movie_list.html"><img src="{% static 'movie_app/img/others.png' %}"></a>
          </div>
        </div>
        <div class="nextdirection top-next">
          <img src="{% static 'movie_app/img/right-arrow.svg' %}">
        </div>
        <div class="leftdirection top-prev">
          <img src="{% static 'movie_app/img/left-arrow.svg' %}">
        </div>
        <!-- Add Pagination -->
      </div>
    </div>
  </section>
{% endblock content %}
<!-- Swiper JS -->

movie_app/templates/movie_app/language.html
{% extends "movie_app/list_views_base.html" %}
{% load static %}


{% block content_list %}
  <h3>Language: {{ language }}</h3>
  <div class="movies">
    {% for object in object_list %}
      <div class="mov">
        <a href="{% url 'movie_app:movie_detail' object.pk object.slug %}">
          <img src="{{ object.cover.url }}">
          <h2 class="movietitle">{{ object.name }}</h2>
        </a>
      </div>
    {% endfor %}
  </div>
{% endblock content_list %}

movie_app/templates/movie_app/nav.html
{% load auto_navbar %}


<li>
  <a href="{% url 'movie_app:home' %}">Home</a>
</li>

<li>
  <a>Genres</a>
  <ul>
    {% for genre in genres %}
      <li>
        {% if genre.level == 1 %}
          <a href="{% url 'movie_app:genre_list' genre %}">{{ genre|capfirst }}</a>
          {% if genre.genresmodel_set %}
            {% include 'movie_app/nav_genre.html' %}
          {% endif %}
        {% endif %}
      </li>
    {% endfor %}
  </ul>
</li>

<li>
  <a>Year</a>
  <ul>
    {% for a_year in year %}
      <li>
        <a href="{% url 'movie_app:year_archive' a_year %}">{{ a_year }}</a>
      </li>
    {% endfor %}
  </ul>
</li>

<li>
  <a>Language</a>
  <ul>
    {% for language in languages %}
      <li>
        <a href="{% url 'movie_app:language_list' language %}">{{ language|capfirst }}</a>
      </li>
    {% endfor %}
  </ul>
</li>

movie_app/templates/movie_app/nav_genre.html
<ul>
  {% for genre in genre.genresmodel_set.all %}
    <li>
      <a href="{% url 'movie_app:genre_list' genre %}">{{ genre|capfirst }}</a>
      {% if genre.genresmodel_set %}
        {% include 'movie_app/nav_genre.html' %}
      {% endif %}
    </li>
  {% endfor %}
</ul>

movie_app/templates/movie_app/search.html
{% extends 'movie_app/list_views_base.html' %}
{% load static %}


{% block content_list %}
  <h3>Search for: {{ request.GET.q }}</h3>
  <div class="movies">
    {% for object in object_list %}
      <div class="mov">
        <a href="{% url 'movie_app:movie_detail' object.pk object.slug %}">
          <img src="{{ object.cover.url }}">
          <h2 class="movietitle">{{ object.name }}</h2>
        </a>
      </div>
    {% endfor %}
  </div>
{% endblock %}

movie_app/templates/movie_app/year.html
{% extends 'movie_app/list_views_base.html' %}
{% load static %}


{% block content_list %}
  <h3>{{ year }}</h3>
  <div class="movies">
    {% for object in object_list %}
      <div class="mov">
        <a href="{% url 'movie_app:movie_detail' object.pk object.slug %}">
          <img src="{{ object.cover.url }}">
          <h2 class="movietitle">{{ object.name }}</h2>
        </a>
      </div>
    {% endfor %}
  </div>
{% endblock content_list %}